accounts/urls.py
from django.urls import path,include
from . import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    path("login/", auth_views.LoginView.as_view(template_name="accounts/login.html"),name='login'),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("signup/", views.SignUp.as_view(), name="signup"),
]

market/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(),name='home'),
    path('loggedin/',views.LoggedinPage,name = 'loggedin'),
    path('loggedout/',views.LoggedoutPage.as_view(),name='loggedout'),
    path('accounts/',include("accounts.urls",namespace = "accounts")),
    path('accounts/',include("django.contrib.auth.urls")),
    path('viewstock/',include("viewstock.urls")),
    path('portfolio/',include("portfolio.urls")),
]

portfolio/urls.py
from django.urls import path, include
from . import views

app_name = 'portfolio'

urlpatterns = [
    path('', views.home, name="portfolio")
]

viewstock/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'viewstock'

urlpatterns = [
    path('',views.home,name='home'),
    path('stockinfo/',views.stockinfo,name='stockinfo'),
    path("data.json/",views.get_data,name='get_data'),
    path("initdata.json/",views.init_get_data,name='init_get_data'),
    path('buystock/',views.buystock,name='buystock'),
    path('stockredirect/',views.stockredirect,name='stockredirect'),
    path('stockinfo/<str:name>',views.test,name="test"),
    path('stockinfo/',views.test,name="stockinfo"),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Young Investor's Competition</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="https://cdn.jsdelivr.net/npm/sweetalert2@10.10.1/dist/sweetalert2.all.min.js"></script>
  <link rel='stylesheet' href='https://cdn.jsdelivr.net/npm/sweetalert2@10.10.1/dist/sweetalert2.min.css'>
  <style media="screen">
  .jumbotron {
      padding: 2rem 1rem;
      margin-bottom: 2rem;
      background-color: #e9ecef;
      border-radius: .3rem;
      padding-top: 2rem;
      margin-top: 2rem
      }
  </style>

  <style media="screen">
      @media screen and (min-width: 0px) and (max-width: 700px) {
        .mobileHidden{
          display:none;
        }
      }

      @media screen and (min-width: 701px) and (max-width: 3000px) {
        .desktopHidden{
          display:none;
        }

      }

  </style>


  </head>


  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand desktopHidden" style="font-size:30px;" href="{% url 'home' %}"><div class="" >YIC</div></a>
      <a class="navbar-brand mobileHidden" style="font-size:30px;" href="{% url 'home' %}"><div class="" >Young Investor's Competition</div></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" style="font-size:20px;" href="{% url 'viewstock:home' %}">View Stocks</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" style="font-size:20px;" href="{% url 'portfolio:portfolio' %}">My Portfolio</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" style="font-size:20px;" href="{% url 'accounts:logout' %}" onclick="return confirm('Are you sure you want to log out?');">Logout</a>
              </li>

        {% else %}
              <li class="nav-item">
                <a class="nav-link" style="font-size:20px;" href="{% url 'accounts:login' %}" class="btn btn-simple">Log in</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" style="font-size:20px;" href="{% url 'accounts:signup' %}" class="btn btn-simple">Sign up</a>
              </li>
        {% endif %}
    </div>
    </nav>

        <div class="container">
          {% block content_container %}

          {% endblock %}
        </div>

       {% block content_nocontainer %}
       {% endblock %}





  </body>
</html>

templates/base2.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Young Investor's Competition</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="https://cdn.jsdelivr.net/npm/sweetalert2@10.10.1/dist/sweetalert2.all.min.js"></script>
  <link rel='stylesheet' href='https://cdn.jsdelivr.net/npm/sweetalert2@10.10.1/dist/sweetalert2.min.css'>
  <style media="screen">
  .jumbotron {
      padding: 2rem 1rem;
      margin-bottom: 2rem;
      background-color: #e9ecef;
      border-radius: .3rem;
      padding-top: 2rem;
      margin-top: 2rem
      }
  </style>

  <style media="screen">
      @media screen and (min-width: 0px) and (max-width: 700px) {
        .mobileHidden{
          display:none;
        }
      }

      @media screen and (min-width: 701px) and (max-width: 3000px) {
        .desktopHidden{
          display:none;
        }

      }

  </style>


  </head>


  <body>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand desktopHidden" style="font-size:30px;" href="{% url 'home' %}"><div class="" >YIC</div></a>
          <a class="navbar-brand mobileHidden" style="font-size:30px;" href="{% url 'home' %}"><div class="" >Young Investor's Competition</div></a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto  mb-2 mb-lg-0">

              {% if user.is_authenticated %}
                      <li class="nav-item">
                        <a class="nav-link" style="font-size:20px;" href="{% url 'viewstock:home' %}">View Stocks</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" style="font-size:20px;" href="{% url 'portfolio:portfolio' %}">My Portfolio</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" style="font-size:20px;" href="{% url 'accounts:logout' %}" onclick="return confirm('Are you sure you want to log out?');">Logout</a>
                      </li>

                {% else %}
                      <li class="nav-item">
                        <a class="nav-link" style="font-size:20px;" href="{% url 'accounts:login' %}" class="btn btn-simple">Log in</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" style="font-size:20px;" href="{% url 'accounts:signup' %}" class="btn btn-simple">Sign up</a>
                      </li>
                {% endif %}

            </ul>
          </div>
        </div>
        </nav>

        <div class="container">
          {% block content_container %}

          {% endblock %}
        </div>

       {% block content_nocontainer %}
       {% endblock %}


      <!-- Comment added by Shrivardhan Goenka -->
      <!-- Comment added by Prakarsh Jhajharia -->





  </body>
</html>

templates/index.html
{% extends "base.html" %}
{% block content_container %}

<h1>Welcome to test</h1>

{% endblock content_container %}

templates/loggedin.html
{% extends "base.html" %}
{% block content_container %}
  <script>
       Swal.fire("Success", "You are now logged in", "success");
  </script>

{% endblock %}

templates/loggedout.html
{% extends "base.html" %}
{% block content_container %}

<script>
     Swal.fire("Success", "You were logged out", "success");
</script>
{% endblock %}